name: Store GPG Key in AWS Secrets Manager

on:
  workflow_dispatch:

jobs:
  store-gpg-key:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Check if GPG Key exists in AWS Secrets Manager
        id: check_secret
        run: |
          set +e
          aws secretsmanager describe-secret --secret-id landslide-monitoring-usb-driver-gpg-key --region ${{ secrets.AWS_REGION }}
          if [ $? -eq 0 ]; then
            echo "secret_exists=true" >> $GITHUB_ENV
          else
            echo "secret_exists=false" >> $GITHUB_ENV
          fi
          set -e
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Create GPG Key in AWS Secrets Manager (if not exists)
        if: env.secret_exists == 'false'
        run: |
          aws secretsmanager create-secret \
            --name landslide-monitoring-usb-driver-gpg-key \
            --secret-string "${{ secrets.GPG_PRIVATE_KEY }}" \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
